// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/postpilot/api/internal/app"
	"github.com/postpilot/api/internal/repositories"
	"github.com/postpilot/api/internal/services"
)

// Injectors from wire.go:

// InitializeApp creates the application with all dependencies wired
func InitializeApp() (*App, error) {
	database, err := ProvideDatabase()
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepositoryWithDB(database)
	authService := ProvideAuthService(userRepository)
	authHandler := app.NewAuthHandler(authService)
	articleService := services.NewArticleService()
	articleHandler := app.NewArticleHandler(articleService, authService)
	openAIClient := ProvideOpenAIClient()
	postGenerationLogRepository := repositories.NewPostGenerationLogRepositoryWithDB(database)
	socialPostStoriesRepository := repositories.NewSocialPostStoriesRepositoryWithDB(database)
	postService := ProvidePostService(openAIClient, postGenerationLogRepository, socialPostStoriesRepository)
	postHandler := app.NewPostHandler(postService, authService)
	diApp := ProvideApp(authHandler, articleHandler, postHandler)
	return diApp, nil
}
